"""Данные гарантов из официального @Xscam_bot (папка «данные о гарантах»)."""

from __future__ import annotations

# Страницы как в боте: 6 + 3 + 10 + 9 = 28
GARANTS_PAGE_SIZES = [6, 3, 10, 9]

GARANTS_DETAILED: list[dict] = [
    # —— стр. 1/4 (элитные, полный формат) ——
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇷🇺",
        "username": "@qw0xx",
        "proofs": "12000+",
        "channel": "@qw0xxproofs",
        "rating": "5.0/5",
        "deal_price": "0",
        "handler": "@vkk1tty",
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇷🇺",
        "username": "@Tulenzentg",
        "proofs": "7000+",
        "channel": "@tulenzentproof",
        "rating": "5.0/5",
        "deal_price": "100",
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇺🇦",
        "username": "@anniiiesh",
        "proofs": "5000+",
        "channel": "@nutiksotz",
        "rating": "5.0/5",
        "deal_price": "0",
        "handler": "@ishnnaa",
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇺🇦",
        "username": "@valywi",
        "proofs": "3500+",
        "channel": "@valywi proofs",
        "rating": "5.0/5",
        "deal_price": "0",
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇺🇦",
        "username": "@Mne_n0xyi",
        "proofs": "2800+",
        "channel": "@slaadkip0xyi",
        "rating": "5.0/5",
        "deal_price": "0",
        "handlers": ["@S4569_agro", "@mittyq1"],
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇺🇦",
        "username": "@frosyyy",
        "proofs": "2800+",
        "rating": "5.0/5",
        "deal_price": "0",
        "handler": "@bsjian",
        "role_label": "Элитный гарант",
    },
    # —— стр. 2/4 ——
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇷🇺",
        "username": "@rilliya",
        "proofs": "2500+",
        "channel": "@shoprilliya",
        "rating": "5.0/5",
        "deal_price": "50",
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "⚡",
        "username": "@Lightowskyy",
        "proofs": "1600+",
        "channel": "@NFT_NEO",
        "rating": "5.0/5",
        "deal_price": "0",
        "handlers": ["@evanescia", "@exaltist", "@quark_doge"],
        "role_label": "Элитный гарант",
    },
    {
        "subgroup": "Элитные гаранты",
        "tier": "elite",
        "flag": "🇺🇦",
        "username": "@Quantixx_1",
        "proofs": "850+",
        "channel": "@quantixxProof",
        "rating": "5.0/5",
        "deal_price": "0",
        "handlers": ["@sparklingbrut"],
        "role_label": "Элитный гарант",
    },
    # —— стр. 3/4 (краткий формат) ——
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@yanikto1",
        "proofs": "7850+",
        "channel": "@naragarantproofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@hikk0l",
        "proofs": "7000+",
        "channel": "@hikk0l_proofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@KitMi_garantik",
        "proofs": "4500+",
        "channel": "@kitmigarant",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@zh0xxz",
        "proofs": "4200+",
        "channel": "@shop_zh0xxz",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@seifdefense",
        "proofs": "3000+",
        "channel": "@fixxnnproofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@Isiieluu",
        "proofs": "3000+",
        "channel": "@axspproofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@Anfix_garant",
        "proofs": "3000+",
        "channel": "@Anfixgarant",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@onlllyffanss",
        "proofs": "2400+",
        "channel": "@otz_onlllyffanss",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@yaemik3",
        "proofs": "2000+",
        "channel": "@yaemik3proofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@harveey0",
        "proofs": "1600+",
        "channel": "@harveeyeshop",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    # —— стр. 4/4 ——
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@n5kiss",
        "proofs": "1350+",
        "channel": "@mishikproofs",
        "list_style": "compact",
        "role_label": "Гарант",
        "senior_admin": "@mishixproofs",
        "rating": "5.0/5",
        "rating_votes": 1,
        "scammers_added": 2354,
        "warns": "1/3",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@qqq_Ayaka_qqq",
        "proofs": "1000+",
        "channel": "@Ayaka_Uk",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@aw1xx",
        "proofs": "1000+",
        "channel": "@aw1xx_proofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@eflawii",
        "proofs": "1000+",
        "channel": "@eflawii_proof",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@grimtagg",
        "proofs": "850+",
        "channel": "@grims_proofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@axel_uii",
        "proofs": "850+",
        "channel": "@axel_prufi",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@lorixdm",
        "proofs": "666+",
        "channel": "@lorixproofs",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇺🇦",
        "username": "@Barashka00",
        "proofs": "600+",
        "channel": "@BarashkaShopAdopt",
        "list_style": "compact",
        "role_label": "Гарант",
    },
    {
        "subgroup": "Гаранты",
        "tier": "regular",
        "flag": "🇷🇺",
        "username": "@FlowerPower",
        "proofs": "1+",
        "channel": "@SHBETOCK",
        "list_style": "compact",
        "role_label": "Гарант",
    },
]